language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"
#  - "5.2"

env:
  - NO_INTERACTION=1 TEST_TIMEOUT=120

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.pher install --dev

script: phpunit --coverage-text --configuration ./tests/phpunit.xml

notify:
  - email
